### ISSUE TITLE
Math equations are not rendered properly

### ISSUE THREAD

**Issue by Okroshiashvili** [getpelican/pelican-plugins#1187] opened 2019-09-10 07:44 UTC
I updated my website theme which is "Elegant" and after that render_math plugin does not render equations.

[Here is the link](https://github.com/Pelican-Elegant/elegant/issues/506) of issue, which I originally thought was due to Elegant update but it seems not.

Any suggestions to solve this problem would be appreciated.

Here are the [picture](https://user-images.githubusercontent.com/20360326/64501021-bc8e8c80-d2d0-11e9-995a-d56020e753bb.png) and my blog [source](https://github.com/Okroshiashvili/Data-Science-Fabric)

**Comment by Lucas-C** [comment] 2019-09-10 09:12
The `render_math` plugin specifies to use it as `render_math` (source: https://github.com/getpelican/pelican-plugins/tree/master/render_math#installation ) not as `pelican_render_math` as you do in your config: https://github.com/Okroshiashvili/Data-Science-Fabric/blob/master/pelicanconf.py#L39
have you tried changing this ?

Also, could you provide your blog generation command log please ? I am especially interested in the plugins logs.

Could you also please provide a minimal formula that produces rendering glitches, in order for us to build unit tests reproducing your issue ?

**Comment by Okroshiashvili** [comment] 2019-09-16 05:53
Hi @Lucas-C . Did not find time to test your suggestion. Now I removed `pelican_render_math` and left only `render_math` plugin and still does not work. Gives me the same error. 

I don't know where to find the blog generation log file. 

The formula which produces the rendering glitches is this one, but note that this formula is not only one.

[\begin{align*}A =
\begin{bmatrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33}
\end{bmatrix}
\end{align*}](url)

**Comment by Lucas-C** [comment] 2019-09-16 07:25
Thanks for the infos.

I was able to reproduce your issue.

The formula you provided is valid based on https://www.mathjax.org demo rendering,
so the issue is probably with the Pelican plugin.

Do you know if it happens with all Latex-syntax based formulas, or only some of them ?
I'm goind to continue investigating...

**Comment by Lucas-C** [comment] 2019-09-16 08:18
I think this is due to the use of `\begin{align*}`
I you drop those start & end tags, the formula will be displayed correctly.

Is it a good enough solution for you, or do you went to dig deeper into this issue ?

**Comment by Okroshiashvili** [comment] 2019-09-16 10:04
It does not happen with all Latex-syntax based formulas. Only some of them are not rendered correctly.

I removed `\begin{align*}` tags but still the same error. Does not render. you can check this [link](https://dsfabric.org/advances-of-linear-algebra-with-python-part-ii)

**Comment by Lucas-C** [comment] 2019-09-16 11:42
Could you try renaming your `.ipynb-meta` files into `.nbdata` files ? _cf._ https://github.com/danielfrg/pelican-ipynb/issues/109

**Comment by Lucas-C** [comment] 2019-09-16 11:45
I added tests to https://github.com/getpelican/pelican-plugins/pull/1188, including one with the formula you provided, and another one based on `.ipynb` & `nbdata` files containing this:

    \begin{align*}A =
    LL^{T}
    \end{align*}

They all pass

**Comment by Okroshiashvili** [comment] 2019-09-16 12:18
@Lucas-C, unfortunately, that does not work. I updated `pelican-ipynb` plugin and changed `.ipynb-meta` to `.nbdata` but still same error.

Can you clone my blog repo and test it locally?

**Comment by Lucas-C** [comment] 2019-09-17 17:10
I have found a lead: the `LL` string is converted to `<span class="caps">LL</span>` which blocks MathJax rendering.
I don't know from where this `caps` CSS class comes from so far.

**Comment by Lucas-C** [comment] 2019-09-17 17:19
Ok, this is due to `tipogrify`.

The simple solution is to disable it: https://github.com/Okroshiashvili/Data-Science-Fabric/blob/master/pelicanconf.py#L105

Another solution could be to play with the `TYPOGRIFY_IGNORE_TAGS` setting in order to find how to selectively disable it on some sections of your blog / theme page structure : https://github.com/getpelican/pelican-plugins/blob/master/render_math/math.py#L242

Another solution could be to suggest a PR to the `render_math` plugin to improve it in order to make `TYPOGRIFY_IGNORE_TAGS`

**Comment by Okroshiashvili** [comment] 2019-09-17 19:06
@Lucas-C  huuuuge thanks. Disabling `TYPOGRIFY` solved the problem

**Comment by Lucas-C** [comment] 2019-09-18 07:04
Great. Feel free to close this issue if your problem is solved

**Closed** 2019-09-18 09:09 UTC
Labels: bug
