### ISSUE TITLE
Error with simple_footnotes when footnote contains markup

### ISSUE THREAD

**Issue by Naereen** [getpelican/pelican-plugins#1022] opened 2018-04-30 23:09 UTC
In this line, `None` should not be returned.
https://github.com/getpelican/pelican-plugins/blob/8d96866a4ec54ff30ada0a5bf68051f95dd1d257/simple_footnotes/simple_footnotes.py#L20

For example, this example `this text[ref]with a footnote with [a link](http://example.com)[/ref]will fail` fails with the following (cryptic) message:
```bash
$ make html
...
CRITICAL: TypeError: sequence item 3: expected str instance, NoneType found
...
```

**Comment by Naereen** [comment] 2018-04-30 23:10
In practice, I simply commented this line `return None` in `simple_footnotes.py`, and everything works fine.

**Comment by Naereen** [comment] 2018-06-06 15:42
Nobody? @justinmayer?

**Comment by justinmayer** [comment] 2018-06-06 16:58
@Naereen: I've never used this plugin. Perhaps consider looking at its modification history and reaching out to folks who have contributed to it.

**Comment by Naereen** [comment] 2018-06-06 17:01
@justinmayer OK, sorry.

@linevych, @stuartlangridge, @mattvonrocketstein, @lindzey and @johnmarkschofield: could one of you please check this issue and the [proposed changed](https://github.com/Naereen/Objectif-Zero-Dechet-2018/commit/d1422c697173e39289a0ce14e1fd8f1715dcbc80#diff-8faae123fbdc94909719bca2d44322a1L24) (in my fork, but I can do the same change here).
Thanks in advance.

**Comment by johnmarkschofield** [comment] 2018-06-11 20:29
Can you fork the main repo and make a pull request with this change? Happy to look at it then, when the fix would help everyone.

**Comment by Naereen** [comment] 2018-06-11 20:51
Hi @johnmarkschofield, thanks for the reply. See #1036.
I don't know if there is automated tests for this extension or this repo.
But I tested the plugin on two blogs, and this tiny change never broke any of my `[ref]...[/ref]` footnote, while letting them use markup.

**Comment by kdeldycke** [comment] 2021-01-04 16:36
`simple-footnotes` plugin has been moved to its own repository at: https://github.com/pelican-plugins/simple-footnotes .

If the problem persist with the last version of this plugin, I propose to report it over there. Else, I guess we can close this issue.

**Comment by justinmayer** [comment] 2021-01-04 16:52
Hi @Naereen! Very sorry for the long delay in reviewing this. You wrote:
> For example, this example `this text[ref]with a footnote with [a link](http://example.com)[/ref]will fail` fails with the following (cryptic) message […]

I added that text to a page and tested with Pelican 4.5.4 and Simple Footnotes 1.0.2, and I couldn't reproduce that error. If you can reproduce the problem reliably, please submit a PR to the [Simple Footnotes repo](https://github.com/pelican-plugins/simple-footnotes) with a test that fails on the current code, followed by a commit that makes that test pass. Thanks for understanding that we can't just merge changes without understanding how, where, and why the problem occurs! 😅

**Closed by justinmayer** 2021-01-04 16:52 UTC

**Comment by Naereen** [comment] 2021-01-04 18:28
@kdeldycke @justinmayer hi, and thanks for your replies.
I'll try to reproduce my bug using the latest versions of Pelican and Simple Footnotes.
But it's likely still present, as the same line from the code I was using two years ago is still there:
https://github.com/pelican-plugins/simple-footnotes/blob/4bf0005eb7e1c3e887eb25e1c5b5f51722c05d3b/pelican/plugins/simple_footnotes/simple_footnotes.py#L20
I will let you know when I tried. (I have two tiny blogs using Pelican but I'm ashamed as I haven't updated either of them in the last months...)

**Comment by Naereen** [comment] 2021-01-04 18:46
![Capture du 2021-01-04 19-38-28](https://user-images.githubusercontent.com/11994719/103567952-f5d70c80-4ec4-11eb-89fd-3b9c975990db.png)
Well I just tried, and now it works! See https://perso.crans.org/besson/cuisine/test-de-pelican.html#footnote on my blog.

Thanks!

**Comment by Naereen** [comment] 2021-01-04 18:58
Oh drat, I still have issues with [my other blog](https://perso.crans.org/besson/zero-dechet/)... I'm trying to find the Markdown code that gives the issue, but the issue is the same as two years ago:
```
USING THIS return None
CRITICAL: sequence item 22: expected str instance, NoneType found
```

**Comment by Naereen** [comment] 2021-01-04 19:08
I haven't found any special Markdown markup that makes the simple-footnotes plugin fails, any foonote with a link inside made my blog failing (with most recent version of the plugin).
I changed the code of `simple-footnotes.py` like this:
```py
-      L.append(getText(n))
+      L.append(getText(n, recursive=recursive))
```

```diff
 diff --git a/plugins/simple_footnotes/simple_footnotes.py b/plugins/simple_footnotes/simple_footnotes.py
 index dc3894f..40a5edc 100644
 --- a/plugins/simple_footnotes/simple_footnotes.py
 +++ b/plugins/simple_footnotes/simple_footnotes.py
 @@ -19,7 +19,7 @@ def getText(node, recursive=False):
          else:
              if not recursive:
                  return None
 -        L.append(getText(n))
 +        L.append(getText(n, recursive=recursive))
      return u"".join(L)
```
