### ISSUE TITLE
org_reader syntax highlighting problems

### ISSUE THREAD

**Issue by fanpeng-kong** [getpelican/pelican-plugins#774] opened 2016-09-11 10:30 UTC
I am having a hard time with source code syntax highlighting when using org_reader. When org export to html used alone, I get expected syntax highlight by using current emacs colour-theme or an additional .css file, i.e. setting `org-html-htmlize-output-type` to `inline-css` or `css`. However when batch exported through org_reader, it seems org_reader has omitted these settings. At least the background colour does not work properly, even using meta data `#+HTML_HEAD: <style>pre.src {background-color: #303030; color: #e5e5e5;}</style>` in an org file does not help either.

Also I guess org_reader can not use the pygments generated .css file as Markdown would do. So could anyone here give me any suggestions on this issue? Many thanks.

**Comment by kkweon** [comment] 2017-07-22 05:28
@fanpeng-kong Did you figure out?
I'm also looking for a way to syntax-highlight source codes using `org_reader`

The problem is

`org_reader` uses org -> html at default. In this conversion, all source codes will be generated with the class name of `src src-{language}`.

For example,

This `org-mode`,
```org
#+BEGIN_SRC python
import numpy as np
A = np.random.randn(32, 32)
print(A)
#+END_SRC
```
will be converted to this html

```html
<pre class="src src-python">
import numpy as np
A = np.random.randn(32, 32)
print(A)
</pre>
```

Not sure how to fix this.

**Comment by justinmayer** [comment] 2018-03-23 10:41
@fanpeng-kong / @kkweon: Were you able to find a solution to your problem here?

**Comment by kkweon** [comment] 2018-03-24 03:07
Not really. I just decided not to use Org for blogging.
I'm okay with closing this issue.

**Comment by justinmayer** [comment] 2018-03-24 06:48
Cheers. Thanks for letting me know.

**Closed by justinmayer** 2018-03-24 06:48 UTC
