### ISSUE TITLE
pandoc_reader plugin breaks `make html'

### ISSUE THREAD

**Issue by whatacold** [getpelican/pelican-plugins#684] opened 2016-02-27 18:08 UTC
I just cloned pelican-plugins repo as `git clone --recursive https://github.com/getpelican/pelican-plugins`,
and set plugins up as below:

```
PLUGIN_PATHS = ['../pelican-plugins']
PLUGINS = ['extract_toc']
MD_EXTENSIONS = (['toc'])
```

then goes the errors when `make html`:

```
$ make html
pelican /home/whatacold/workspace/github/blogs/content -o /home/whatacold/workspace/github/blogs/output -s /home/whatacold/workspace/github/blogs/pelicanconf.py 
ERROR: Could not process ./redis.md
  | OSError: [Errno 2] No such file or directory
(many other similar errors are omitted)
```

so I ran it again with debug on, and the traceback was below:

```
$ make DEBUG=1 html
...
DEBUG: Read file redis.md -> Article
ERROR: Could not process ./redis.md
  | OSError: [Errno 2] No such file or directory
  |___
  | Traceback (most recent call last):
  |   File "/home/whatacold/workspace/virtualenv/pelican/lib/python2.7/site-packages/pelican/generators.py", line 514, in generate_context
  |     context_sender=self)
  |   File "/home/whatacold/workspace/virtualenv/pelican/lib/python2.7/site-packages/pelican/readers.py", line 508, in read_file
  |     content, reader_metadata = reader.read(path)
  |   File "/home/whatacold/workspace/github/pelican-plugins/pandoc_reader/pandoc_reader.py", line 34, in read
  |     stdout = subprocess.PIPE)
  |   File "/usr/lib64/python2.7/subprocess.py", line 710, in __init__
  |     errread, errwrite)
  |   File "/usr/lib64/python2.7/subprocess.py", line 1335, in _execute_child
  |     raise child_exception
  | OSError: [Errno 2] No such file or directory
```

It shown that there is something wrong with `pandoc_reader` plugin,
and `make html` works ok after simply remove it.

Hope someone would fix this, thanks.

**Comment by whatacold** [comment] 2016-02-28 01:11
Well, pelican version is 3.6.3:

    $ pelican --version
    3.6.3

**Comment by Scheirle** [comment] 2016-03-09 14:15
Duplicate of https://github.com/getpelican/pelican-plugins/issues/582 ?
Quick fix do not include the whole pelican-plugins repo in `PLUGIN_PATHS`. Instead create a separate folder and symlink only your used plugins.

**Comment by vsbuffalo** [comment] 2016-08-12 23:51
I have this issue too, with `pandoc_reader`. Are there updates on this?

**Comment by vsbuffalo** [comment] 2016-08-18 04:21
For the record — this had a simple (but embarrassing) for me; pandoc was not in my `$PATH` and this led to this exact error.

**Comment by justinmayer** [comment] 2018-03-23 10:33
Closing due to inactivity. Please feel free to comment here if you feel the issue should be re-opened.

**Closed by justinmayer** 2018-03-23 10:33 UTC
